name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정 (UTC) - 별 5개로 수정

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Waka Readme Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LANGUAGE: "true"
          SHOW_OS: "true"
          SHOW_EDITORS: "true"
          SHOW_PROJECTS: "true"
          SHOW_TIMEZONE: "true"
          SHOW_COMMIT: "true"
          SHOW_LINES_OF_CODE: "true"
          SHOW_PROFILE_VIEWS: "false"  # 에러 원인 비활성화
          SHOW_LOC_CHART: "false"      # 차트 기능 비활성화 (안정성)
          SHOW_DAYS_OF_WEEK: "true"    # 요일별 활동
          SHOW_SHORT_INFO: "true"      # 간단한 정보
          SHOW_UPDATED_DATE: "true"    # 업데이트 날짜
          SHOW_TOTAL_CODE_TIME: "true" # 총 코딩 시간
          LOCALE: "en"                 # 언어 설정
