name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정 (UTC) - 별 5개 필요

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Waka Readme
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LANGUAGE: "true"
          SHOW_OS: "true"
          SHOW_EDITORS: "true"
          SHOW_PROJECTS: "true"
          SHOW_TIMEZONE: "true"
          SHOW_COMMIT: "true"
          SHOW_LINES_OF_CODE: "true"
          SHOW_PROFILE_VIEWS: "false"  # 에러 방지
          SHOW_DAYS_OF_WEEK: "true"
          SHOW_SHORT_INFO: "true"
          SHOW_LOC_CHART: "false"
          LOCALE: "en"
