name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Waka Readme Stats
        uses: anmol098/waka-readme-stats@v4.0.0  # 특정 버전 고정
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LANGUAGE: "true"
          SHOW_OS: "true"
          SHOW_EDITORS: "true"
          SHOW_PROJECTS: "true"
          SHOW_TIMEZONE: "true"
          SHOW_COMMIT: "true"
          SHOW_LINES_OF_CODE: "true"
          SHOW_PROFILE_VIEWS: "false"
          SHOW_LOC_CHART: "false"
          SHOW_DAYS_OF_WEEK: "true"
          SHOW_SHORT_INFO: "true"
          SHOW_UPDATED_DATE: "true"
          SHOW_TOTAL_CODE_TIME: "true"
          LOCALE: "en"
